url: https://rachelsyli.github.io
baseurl:

# Site settings
title: Rachel Li
email: rachelsyli@domain.com
description: "Marketing and communications enthusiast always looking for new challenges."

# Team names, titles and social links
# people:
# - name: Rachel Li
#   pic: 1
#   position: Marketing
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rachelsyli
  - title: github
    url: http://github.com/rachelsyli

# Build settings
markdown: kramdown
permalink: pretty